name: Build Crossplatform Binary

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-x64, win-x64, mac-x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build Bun Project
        run: bun build.mjs

      - name: Create Binary with jpkg
        shell: bash
        run: |
          bun add -d jpkg
          npx jpkg dist/index.js --output gm-${{ matrix.platform }} --target ${{ matrix.platform }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gm-${{ matrix.platform }}
          path: gm-${{ matrix.platform }}
